build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py

publish:
    docker:
        repo: $$sanjaydas/cicd_demoapp
        tag: latest
        username: $$sanjaydas
        password: $$Nitai1Gaur1
        email: $$sanjadas@cisco.com
